### PR TITLE
WIP install OADP operator with the backup chart

### PR DESCRIPTION
**Pull request by birsanv**
Signed-off-by: Valentina Birsan <vbirsan@redhat.com>

https://github.com/stolostron/backlog/issues/18711

### CODE REVIEW

**Comment by birsanv** [comment]
@zkayyali812 this PR brings back the oadp operator installation remove in 2.4 because the operator was tech preview

https://github.com/stolostron/cluster-backup-chart/pull/12

This is an fyi / fya for you if you can review and let me know if you see any issues with this

Basically, with this change, when somebody installs the backup chart, it will also install the oadp operator, in the ACM ns

**Comment by zkayyali812** [comment]
Hi @birsanv ,

I took a glance at the PR and had some questions about this that I am working to clear up with our architect @joeg-pro before merging.

I see we are installing the OADP operator from `community-operators`. This seems strange as of now, and I think we would want to ensure that this is acceptable. In the case of MCE, we install from the published Red Hat catalogsource, `redhat-operators`, which we have control over.

The InstallPlanApproval is also Automatic, and this does not link to a versioned channel (like release-2.4) for z-stream fixes, but rather to a `stable` channel as a whole. It appears that it is possible for the `stable` channel for OADP to install more than just z-stream fixes automatically.

Please keep this PR held until we are able to clear up the above points.

**Comment by birsanv** [comment]
@zkayyali812 thank you

Issues:
1. I see we are installing the OADP operator from community-operators. 
The oadp operator should be GA any day now ( they gave us the end of Jan as the timeline so I have to check with them when it will actually happen )
I had a scrum call with @jnpacker today and the reason I opened this PR is because I hoped I could check in the update so we can test it ; and make the channel update when OADP is part of `redhat-operators`. If this is a no-go then that's fine
2. The InstallPlanApproval is also Automatic, and this does not link to a versioned channel (like release-2.4) for z-stream fixes
I think this will change once the oadp operator will be made available with the `redhat-operators`

**Comment by birsanv** [comment]
I am told the oadp operator should be available with `redhat-operators` tomorrow
I'll update the PR and ask for review again @zkayyali812 thanks

**Comment by joeg-pro** [comment]
@birsanv This is good news.

**Comment by birsanv** [comment]
@zkayyali812 I am happy to report back on the oparator being available on the redhat channel

Can you please review again

I did not understand your comment on the `installPlanApproval: Automatic` not being linked to a versioned channel
And I am not quite familiar with operator installation

Should I change that to `installPlanApproval: Manual` ?
Basically I want the MCH hub 
- to enable the backup chart by default
- which means this hook to install the OADP operator will be called ; I want the operator to install with no interaction from the user
- when MCH uninstalls or disabled backup  using `enableClusterBackup: false`( which I am not sure we need it as an option anymore since we are GA in 25 ) - I want the OADP operator to be uninstalled
- when MCH installs a new version or upgrades , I want the chart to upgrade > reinstall the oadp operator

Do I have the right options for this to happen ?

```
oadpOperator:
  name: redhat-oadp-operator
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: oadp-operator.v1.0.0
```

**Comment by zkayyali812** [comment]
Hi @birsanv ,

To clarify about my point regarding the `installplanapproval`, this likely isn't relevant anymore now that you are pointing to a `redhat-operators` catalogsource. 
With an Automatic installPlanApproval, if there is a later update, it will automatically install for the user. This likely would have been a problem coming from `community-operators` since the `stable` community version could release breaking changes. However since we are pinning to a `redhat-operators` catalogsource, it is easier to ensure compatibility with the latest OADP. This would allow the user to ensure OADP is installed with no extra steps, like ensuring an installplan is approved manually. 

Regarding this point - 
`when MCH installs a new version or upgrades , I want the chart to upgrade > reinstall the oadp operator`
With an `installPlanApproval` of Automatic, OADP will upgrade anytime an update is available to the OADP `stable` channel in the `redhat-operators catalogsource. This may not necessarily be when the MCH upgrades. 
At MCH installtime we will install the latest OADP available in the stable channel

As long as cluster-backup would like to pin to the latest `redhat-operators` OADP, and not ensure a specific version, this is acceptable and the subscription values shown are correct.

Also would we like to ensure the OADP subscription is installed in a specific namespace? Currently we stand up cluster-backup in the namespace of the MCH CR. If this PR is merged as is, MCH would install the OADP operator as well in that namespace.
Assuming we would like to install it in a separate namespace, this would likely require updates to MCH Operator as well. FYI @JakobGray 
We would also need to update our finalization logic if we were to keep it in the namespace of the MCH.

**Comment by birsanv** [comment]
@zkayyali812 thanks for the quick response !

All 3 points are clear and good 

As for the ns where the oadp operator will be installed - yes, we want to have the oadp operator installed in the MCH ns
This was the plan in 2.4 too

**Comment by zkayyali812** [comment]
@birsanv np !
I think we will need to test if deleting the appsub/helmrelease will terminate both the subscription and the CSV if installed in the MCH namespace first before merging this PR.
I suspect it will only delete the subscription and the CSV will remain as of now.

I think we will also need to do further chart updates to ensure that we are passing down things like nodeSelector, tolerations, and proxyconfigurations to the OADP operator if configured, but perhaps we can get this in later in a different PR.

**Comment by birsanv** [comment]
@zkayyali812 >> Would it be a significant rework to ensure that the OADP subscription/entire cluster-backup chart are installed in a different namespace?

This will actually simplify things :) .. the only reason I was trying to get this installed into the MCH ns is because this was a request I got from installer in 2.4.1 - it must be somewhere in the old PR , I though that MCH wants to have all resources it installs in the same ns with MCH

Can we create the ns if not available Zack ? This is the one unknown with this 

@sahare this should help address the issue with the chart delete, where the oadp cvs stays around
And delete the NS on chart uninstall

**Comment by zkayyali812** [comment]
That sounds great!

Install can update to create both the namespace and the operatorgroup as part of the MCH Operator. We will then lay down the entire cluster-backup chart in that namespace. This allows the MCH O to ensure these resources are cleaned up and managed properly.

As part of this, we will need to update this chart a bit more to ensure we are passing down the name of the NS and subscription from MCHO to the chart.

Since this PR will require more work for installer squad to consume, we will need to leave this PR held until we can get this assigned to someone on Install squad to make the updates to both the MCH Operator and this chart.

**Pull request closed without merging**
